### ISSUE TITLE
Backend&Frontend/Set up CI (CO-01)

### ISSUE THREAD

**Issue by lysnikolaou** [lysnikolaou/eatandmeet#13]
Set up CI, in order for PRs to always get tested, before they get merged.

**Comment by lysnikolaou** [comment]
@nitzanashi @d151 Would you like for the CI builds to also test the frontend and if yes, how are you going to test it?

**Comment by nitzanashi** [comment]
I'll try to Write `.travis.yml` for the frontend ASAP

**Comment by lysnikolaou** [comment]
@nitzanashi you can just commit new pushes to my PR, in order to only have one `.travis.yml` file.
